### PR TITLE
Misc updates

### PR DESCRIPTION
**Pull request by brockboland**
This one is long and I'm sorry, but most of it is pod updates in the Example project.

- Update CocoaPods to 1.1.1
- Update KIF
- Update version number in the podspec to 0.9.1
- iOS 10 simulator no longer allows the `MFMailComposeViewController` to be used, so we can't test for "simulator is borked" alert in the simulator
- ~Bump minimum iOS version to 8~
- Bump the example project to iOS 8 deployment target

@vokal/ios-developers code review please?

### CODE REVIEW

**Comment by vokal-isaac** [comment]
Why raise the minimum iOS version on the pod?

**Comment by designatednerd** [comment]
@vokal-isaac Xcode 8 does not support building for SDKs lower than iOS 8.

**Comment by brockboland** [comment]
And the KIF that supports iOS 10 doesn't support iOS 8

**Comment by vokal-isaac** [comment]
Building for the SDK ≠ supporting deployment to the version.  Unless we're using things that aren't available on iOS 7, I think the minimum deployment target should be left at 7.

**Comment by brockboland** [comment]
Fair enough. Rolling back.

**Review by vokal-isaac — APPROVED** [review]
LGTM

**Review by designatednerd — APPROVED** [review]

**Comment by brockboland** [comment]
@designatednerd @vokal-isaac one more tweak: I switched travis to use `scan`, since `xctool` wasn't cooperating. Cool?

**Review by vokal-isaac — APPROVED** [review]
SLGTM

**Pull request merged**
