### PR TITLE
Framework support

### PR DESCRIPTION
**Pull request by brockboland**
CocoaPods can't make a framework for header-only specs. This change just adds empty implementation files for two subspecs that only had headers. `VOKKeyPathHelper` still can't be used in Swift projects (since it defines macros), but at least it will compile correctly when included in projects using `use_frameworks`.

@vokal/ios-developers what say you?

### CODE REVIEW

**Review by designatednerd — APPROVED** [review]

**Comment by brockboland** [comment]
Now that Travis is working again, this is green. Anyone else want to weigh in?

**Review by bryanluby — APPROVED** [review]
LGTM

**Comment by vokal-isaac** [comment]
I suspect that this isn't necessary for `VOKIBHelpers` as I wouldn't expect `VOKIBHelpers.h` to be included anywhere—it's only there to be indexed by Xcode, causing IB to recognize whatever's put in there...  But I'm not completely certain whether it works as-is in a `use_frameworks!` situation.

**Comment by brockboland** [comment]
That's a good point. Let me pull that one back out of there

**Comment by vokal-isaac** [comment]
Should the podspec be updated to bump the version number?

**Comment by brockboland** [comment]
Nope: it was already bumped to 0.9.1, which will be the next tag once this is merged.

**Review by vokal-isaac — APPROVED** [review]
(:goat:,)

**Pull request merged**
