### PR TITLE
Add OS X and tvOS targets to the example project

### PR DESCRIPTION
**Pull request by chillpop**
I added targets for the supported platforms.  There are no tests for those platforms, but Travis should be able to compile them which provides some assurance that the library will work.

@vokal/ios-developers, "code" review?  The diff is huge but I think the relevant changes are:
- at the top 
  - .travis.yml
  - example Podfile
- source files for new targets (towards the middle)
  - Example/VOKUtilities-OSX/main.m
  - Example/VOKUtilities-tvOS/AppDelegate.m)

### CODE REVIEW

**Comment by brockboland** [comment]
LGTM once we figure out what's up with Travis

**Comment by chillpop** [comment]
Travis is fixed: it is now passing on all platforms.  I added the test to all appropriate platforms.  They are running fine on OS X, but xctool is not seeing the tests for tvOS.  They run from Xcode just fine.

**Comment by brockboland** [comment]
:+1:

**Comment by chillpop** [comment]
tagged and `pod trunk push`'d

**Pull request merged**
